services:
  lldap:
    image: lldap/lldap:stable
    restart: unless-stopped
    ports:
      - "17170:17170"
    volumes:
      - ${LUX_VOLUMES:?}/lldap/data:/data
    environment:
      - LLDAP_LDAP_BASE_DN=dc=luxeria,dc=ch
      - LLDAP_KEY_FILE= # empty
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lldap.rule=Host(`lldap.luxeria.ch`)"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"
    env_file:
       - path: ${LUX_VOLUMES:?}/lldap/secrets.env
         required: true
    networks:
      ldap:
      traefik:

networks:
    # Needs to be created manually with:
    #   docker network create ldap
    ldap:
        name: ldap
        external: true
    traefik:
        name: traefik
        external: true
