version: "3"

services:
  router:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      # websecure entry point
      - "443:443"
      # video entry point for Jitsi
      - "10000:10000/udp"
      # internal entry point
      - "8080:8080"
    volumes:
      - ./conf.d:/etc/traefik/conf.d:z # rw for internal-allowlist.yaml
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro,z
      - ${LUX_VOLUMES:?}/traefik/internal-allowlist.yaml:/etc/traefik/conf.d/internal-allowlist.yaml:ro,z
      - ${LUX_VOLUMES:?}/traefik/acme:/etc/traefik/acme:z
      - ${LUX_VOLUMES:?}/traefik/htpasswd:/etc/traefik/htpasswd:ro,z
    networks:
      - traefik
      - dockerapi
  dockerapi:
    image: ghcr.io/tecnativa/docker-socket-proxy
    restart: unless-stopped
    expose:
      - "2375"
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    healthcheck:
      # Workaround for https://github.com/Tecnativa/docker-socket-proxy/issues/21
      #
      # While this health check does _not_ actually test the if persistent
      # connection between Treafik and HAProxy is still alive, it still works
      # because this health check causes an event in `docker event -f type=container`.
      # This in turn causes the persistent connection between Traefik and HAProxy
      # to receive at least one container event every 5 minutes, therefore
      # not triggering the default 10 minute idle timeout of HAProxy.
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:2375/_ping"]
      interval: 10s
    networks:
      - dockerapi
networks:
  # Needs to be created manually with:
  #   docker network create --subnet=172.19.0.0/16 traefik
  traefik:
    external: true
    name: traefik
  # For Docker API access
  dockerapi: