version: "3"

services:
  router:
    image: traefik:v2.10
    restart: unless-stopped
    ports:
      # websecure entry point
      - "443:443"
      # video entry point for Jitsi
      - "10000:10000/udp"
      # internal entry point
      - "8080:8080"
    volumes:
      - ./conf.d:/etc/traefik/conf.d:z
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro,z
      - /var/data/Volumes/traefik/internal-allowlist.yaml:/etc/traefik/conf.d/internal-allowlist.yaml:ro,z
      - /var/data/Volumes/traefik/acme:/etc/traefik/acme:z
      - /var/data/Volumes/traefik/htpasswd:/etc/traefik/htpasswd:ro,z
    networks:
      - traefik
      - dockerapi
  dockerapi:
    image: ghcr.io/tecnativa/docker-socket-proxy
    restart: unless-stopped
    expose:
      - "2375"
    environment:
      - CONTAINERS=1
      - NETWORKS=1
      - SERVICES=1
      - TASKS=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,z
    networks:
      - dockerapi
networks:
  # Needs to be created manually with:
  #   docker network create --subnet=172.19.0.0/16 traefik
  traefik:
    external: true
    name: traefik
  # For Docker API access
  dockerapi: