accessLog: {}
api: {}

certificatesResolvers:
   letsencrypt:
     acme:
       email: lux@esheep.ch
       storage: /etc/traefik/acme/letsencrypt.json
       tlsChallenge: {}

entryPoints:
  # Default HTTPS entry point. Exposed to the Internet.
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  # UDP entry point used for Jitsi. Exposed to the Internet.
  video:
    address: ':10000/udp'
    udp:
      timeout: 10s
  # Internal HTTP entry point. Only exposed on the internal LAN,
  # only allows access from internal source IPs.
  internal:
    address: ":8080"
    http:
      middlewares:
        - "internal-allowlist@file"

log:
  level: INFO

providers:
  # Docker API access via dockerapi container
  docker:
    exposedByDefault: false
    endpoint: "tcp://dockerapi:2375"
    network: traefik
  file:
    directory: /etc/traefik/conf.d
